print("1 po angielsku: %s \n2 po angielsku: %s" % ('one','two'))
print("1 po angielsku: {} \n2 po angielsku: {}".format('one','two'))
print()
print("Cyfra %d poprzedza %d." % (7,8))
print("Cyfra {} poprzedza {}." .format(7,8))
print()
print("Rekord świata na 100m to %f ustanowił go %s." % (9.58,'Usain Bolt'))
print("Rekord świata na 100m to {} ustanowił go {}.".format(9.58,'Usain Bolt'))
print()
print("Rekord świata na 100m to %.2f ustanowił go %s." % (9.58,'Usain Bolt'))
print("Rekord świata na 100m to {:.2f} ustanowił go {}.".format(9.58,'Usain Bolt'))
print()
print("Rekord świata na 100m padł %s i wynosi %.1f sekund - wow!" %('16 sierpnia 2009',9.58))
print("Rekord świata na 100m padł {} i wynosi {:.1f} sekund - wow!".format ('16 sierpnia 2009',9.58))
